# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/morfologico/Desktop/PickingPoint

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/morfologico/Desktop/PickingPoint

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morfologico/Desktop/PickingPoint/CMakeFiles /home/morfologico/Desktop/PickingPoint//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morfologico/Desktop/PickingPoint/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/Application

# Build rule for target.
bin/Application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bin/Application
.PHONY : bin/Application

# fast build rule for target.
bin/Application/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/build
.PHONY : bin/Application/fast

src/entryPoint.o: src/entryPoint.cpp.o
.PHONY : src/entryPoint.o

# target to build an object file
src/entryPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/entryPoint.cpp.o
.PHONY : src/entryPoint.cpp.o

src/entryPoint.i: src/entryPoint.cpp.i
.PHONY : src/entryPoint.i

# target to preprocess a source file
src/entryPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/entryPoint.cpp.i
.PHONY : src/entryPoint.cpp.i

src/entryPoint.s: src/entryPoint.cpp.s
.PHONY : src/entryPoint.s

# target to generate assembly for a file
src/entryPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/entryPoint.cpp.s
.PHONY : src/entryPoint.cpp.s

src/pickingPoint.o: src/pickingPoint.cpp.o
.PHONY : src/pickingPoint.o

# target to build an object file
src/pickingPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/pickingPoint.cpp.o
.PHONY : src/pickingPoint.cpp.o

src/pickingPoint.i: src/pickingPoint.cpp.i
.PHONY : src/pickingPoint.i

# target to preprocess a source file
src/pickingPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/pickingPoint.cpp.i
.PHONY : src/pickingPoint.cpp.i

src/pickingPoint.s: src/pickingPoint.cpp.s
.PHONY : src/pickingPoint.s

# target to generate assembly for a file
src/pickingPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/pickingPoint.cpp.s
.PHONY : src/pickingPoint.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/Application.dir/build.make CMakeFiles/bin/Application.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/Application"
	@echo "... src/entryPoint.o"
	@echo "... src/entryPoint.i"
	@echo "... src/entryPoint.s"
	@echo "... src/pickingPoint.o"
	@echo "... src/pickingPoint.i"
	@echo "... src/pickingPoint.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

